-- StarRocks Manager 初始化 Schema (MySQL)

CREATE TABLE IF NOT EXISTS connections (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  host VARCHAR(255) NOT NULL,
  port INTEGER NOT NULL DEFAULT 9030,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL DEFAULT '',
  default_db VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_used_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  `key` VARCHAR(255) PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS db_metadata_cache (
  id           INTEGER PRIMARY KEY AUTO_INCREMENT,
  connection_id VARCHAR(255) NOT NULL,
  db_name      VARCHAR(255) NOT NULL,
  table_count  INTEGER NOT NULL DEFAULT 0,
  view_count   INTEGER NOT NULL DEFAULT 0,
  mv_count     INTEGER NOT NULL DEFAULT 0,
  cached_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY idx_conn_db (connection_id, db_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS users_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS roles_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS resource_groups_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS catalogs_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS functions_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS variables_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS materialized_views_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS broker_load_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS routine_load_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pipes_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tasks_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS task_runs_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS task_runs_all_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS nodes_cache (
  connection_id VARCHAR(255) PRIMARY KEY,
  data          LONGTEXT NOT NULL,
  cached_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS command_log (
  id            INTEGER PRIMARY KEY AUTO_INCREMENT,
  session_id    VARCHAR(255) NOT NULL,
  source        VARCHAR(255) NOT NULL DEFAULT 'unknown',
  sql_text      TEXT NOT NULL,
  status        VARCHAR(50) NOT NULL DEFAULT 'success',
  error_message TEXT,
  row_count     INTEGER DEFAULT 0,
  duration_ms   INTEGER DEFAULT 0,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_command_log_session_source (session_id, source),
  INDEX idx_command_log_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_users (
  id            INTEGER PRIMARY KEY AUTO_INCREMENT,
  username      VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  display_name  VARCHAR(255) DEFAULT '',
  role          VARCHAR(50) NOT NULL DEFAULT 'viewer',
  is_active     TINYINT DEFAULT 1,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  last_login_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clusters (
  id          INTEGER PRIMARY KEY AUTO_INCREMENT,
  name        VARCHAR(255) NOT NULL UNIQUE,
  host        VARCHAR(255) NOT NULL,
  port        INTEGER NOT NULL DEFAULT 9030,
  username    VARCHAR(255) NOT NULL,
  password    VARCHAR(255) NOT NULL DEFAULT '',
  default_db  VARCHAR(255) DEFAULT '',
  description TEXT DEFAULT NULL,
  is_active   TINYINT DEFAULT 1,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_cluster_access (
  user_id    INTEGER NOT NULL,
  cluster_id INTEGER NOT NULL,
  PRIMARY KEY (user_id, cluster_id),
  FOREIGN KEY (user_id)    REFERENCES sys_users(id) ON DELETE CASCADE,
  FOREIGN KEY (cluster_id) REFERENCES clusters(id)  ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sys_sessions (
  token       VARCHAR(255) PRIMARY KEY,
  user_id     INTEGER NOT NULL,
  cluster_id  INTEGER,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at  TIMESTAMP NOT NULL,
  FOREIGN KEY (user_id)    REFERENCES sys_users(id) ON DELETE CASCADE,
  FOREIGN KEY (cluster_id) REFERENCES clusters(id)  ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
